# Staged pre-commit configuration
# This runs hooks in stages - start with fast ones, add slower ones over time

default_language_version:
  python: python3.12

repos:
  # STAGE 1: Fast file checks (these complete quickly)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: check-merge-conflict
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: requirements-txt-fixer

  # STAGE 2: Python syntax check (fast)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: debug-statements

  # STAGE 3: Python formatting
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args: [--line-length=120]
    files: ^(cli/|\.claude/scripts/|[^/]+\.py$)

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: [--profile=black, --line-length=120]
    files: ^(cli/|\.claude/scripts/|[^/]+\.py$)

  # STAGE 4: Linting (configured via .flake8)
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    # Configuration is in .flake8 file
    files: ^(cli/|\.claude/scripts/|[^/]+\.py$)

  # STAGE 5: Type checking (configured via mypy.ini)
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
  - id: mypy
    args: [--config-file=mypy.ini, --namespace-packages, --explicit-package-bases]
    files: ^(cli/|\.claude/scripts/)
    exclude: ^hf-space/WORKING_FILES/

  # Security checks (only on our code)
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: [-ll, -i]
    files: ^(cli/|\.claude/scripts/|[^/]+\.py$)
    exclude: ^tests/

  # YAML formatting
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent=2]
    files: \.(yaml|yml)$
    exclude: ^(microsoft-promptwizard/|hf-deployment/|nextjs-app/\.next/)

  # Markdown linting
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
  - id: markdownlint
    args: [--fix]
    files: \.md$
    exclude: ^(microsoft-promptwizard/|hf-deployment/|node_modules/)

# Exclude third-party and generated code
exclude: |
  (?x)^(
    attic/.*|
    microsoft-promptwizard/.*|
    hf-deployment/.*|
    docs/sales/.*|
    venv/.*|
    \.venv/.*|
    node_modules/.*|
    nextjs-app/node_modules/.*|
    nextjs-app/\.next/.*|
    \.git/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    \.mypy_cache/.*|
    build/.*|
    dist/.*|
    .*\.egg-info/.*
  )$
