[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/tags"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

# Don't set PORT - Railway will provide it
# Don't set OLLAMA_HOST - we'll use Railway's PORT