[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/tags"
healthcheckTimeout = 600
startCommand = ""
restartPolicyType = "ON_FAILURE"

[variables]
OLLAMA_HOST = "0.0.0.0:11434"
PORT = "11434"