answer_format: Present the enhanced prompt with clear improvements and reasoning.
base_instruction: Transform the weak prompt into a detailed, specific, and effective prompt.
few_shot_count: 3
generate_expert_identity: true
generate_intent_keywords: true
generate_reasoning: true
max_eval_batches: 3
min_correct_count: 2
mutate_refine_iterations: 3
mutation_rounds: 3
num_train_examples: 20
prompt_technique_name: critique_n_refine
questions_batch_size: 1
refine_instruction: true
refine_task_eg_iterations: 2
seen_set_size: 25
style_variation: 5
task_description: You are an expert prompt engineer. You will be given a basic prompt that needs improvement.
top_n: 3
unique_model_id: qwen3-4b
