[project]
name='driftguard'
version='0.1.0'
dependencies=['fastapi','uvicorn','pydantic','pydantic-settings','pyyaml','httpx']
[project.optional-dependencies]
dev=['pytest','pytest-asyncio','mypy','ruff']
[build-system]
requires=['setuptools','wheel']
build-backend='setuptools.build_meta'
