version: '3.8'

# Development override - uses local Redis with exposed ports
services:
  redis:
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=  # No password in dev
    command: redis-server --appendonly yes --loglevel debug

  app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - REDIS_URL=redis://redis:6379
      # Security features configurable in dev
      - ENABLE_WEBHOOK_VALIDATION=${ENABLE_WEBHOOK_VALIDATION:-true}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - ENABLE_IP_WHITELIST=${ENABLE_IP_WHITELIST:-false}
      - ENABLE_REPLAY_PROTECTION=${ENABLE_REPLAY_PROTECTION:-true}
      - ENABLE_ASYNC=${ENABLE_ASYNC:-true}
    command: npm run start:dev