version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: driftguard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - driftguard-network

  app:
    build: .
    container_name: driftguard-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - ENABLE_WEBHOOK_VALIDATION=true
      - ENABLE_RATE_LIMITING=true
      - ENABLE_IP_WHITELIST=true
      - ENABLE_REPLAY_PROTECTION=true
      - ENABLE_ASYNC=true
      - LOG_LEVEL=info
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - driftguard-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis-data:
    driver: local

networks:
  driftguard-network:
    driver: bridge