version: '1.0'
threshold: 0.85  # CI fails if win_rate < 0.85
model: mock      # Using mock for zero-cost testing

test_prompts:
- Write a Python function to calculate the factorial of a number
- Explain the concept of recursion in programming
- Create a REST API endpoint for user authentication
- Generate unit tests for a shopping cart class
- Describe the differences between SQL and NoSQL databases

evaluation:
  metrics:
  - clarity
  - specificity
  - completeness
  - actionability
  timeout: 30
  batch_size: 10

metadata:
  project: PromptOps Demo
  team: Engineering
  environment: ci
