# PromptWizard Configuration for Seed Pair Generation
# Compatible with Microsoft PromptWizard Framework
# Optimized for PromptEvolver 3.0 training data generation

# Core PromptWizard Settings
prompt_technique_name: "critique_n_refine"
unique_model_id: "qwen2.5-7b"

# Optimization Parameters
mutate_refine_iterations: 3      # Number of mutation+refinement cycles
mutation_rounds: 3               # Mutations per iteration
refine_instruction: true         # Enable instruction refinement
refine_task_eg_iterations: 2     # Refinement iterations for examples

# Generation Control
style_variation: 5               # Number of prompt variations to generate
questions_batch_size: 1          # Batch size for evaluation
min_correct_count: 2             # Minimum correct answers for acceptance
max_eval_batches: 3              # Maximum evaluation batches
top_n: 3                         # Top performing prompts to keep

# Task Definition
task_description: "You are an expert prompt engineer specializing in prompt optimization. You will be given basic, weak prompts that need to be transformed into detailed, specific, and highly effective prompts."

base_instruction: "Transform the weak prompt into a comprehensive, professional prompt by adding appropriate context, specificity, structure, and requirements."

answer_format: "Present the enhanced prompt with clear improvements including role context, specific requirements, output format, and success criteria."

# Training Data Configuration  
seen_set_size: 25                # Training examples to use
few_shot_count: 3                # Examples in few-shot learning
num_train_examples: 20           # Synthetic training examples

# Generation Features
generate_reasoning: true         # Include reasoning for improvements
generate_expert_identity: true   # Assign expert personas
generate_intent_keywords: true   # Extract intent keywords

# Model Parameters
temperature: 0.7                 # Creativity vs consistency balance
max_tokens: 1024                # Maximum response length

# Domain-Specific Settings
domains:
  Analytics:
    expert_identity: "Senior Business Intelligence Analyst"
    focus_areas: ["data analysis", "reporting", "insights", "metrics", "visualization"]
    
  Coding: 
    expert_identity: "Senior Software Engineer"
    focus_areas: ["implementation", "architecture", "best practices", "optimization", "testing"]
    
  Content:
    expert_identity: "Marketing Content Specialist" 
    focus_areas: ["copywriting", "audience targeting", "brand voice", "engagement", "persuasion"]
    
  Cross-Domain:
    expert_identity: "Strategic Consultant"
    focus_areas: ["problem solving", "process optimization", "stakeholder management", "integration"]

# Quality Thresholds
quality_requirements:
  minimum_length_ratio: 2.0      # Enhanced should be 2x longer than original
  minimum_quality_score: 0.65    # Overall quality threshold
  required_improvements: 3        # Minimum improvement areas

# Output Configuration
output_format:
  include_metadata: true
  include_reasoning: true
  include_quality_scores: true
  schema_version: "1.0"