name: DriftGuard Gate (example)
on:
  pull_request:

permissions:
  contents: read

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - run: echo '{"status":"pass","summary":"demo"}' > driftguard-capsule.json
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with: 
          name: driftguard-capsule
          path: driftguard-capsule.json