name: pre-commit

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install pre-commit
      run: python -m pip install -U pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
